version: '3'

services:
  nginx:
    image: "nginx:1.25.0"
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./index.php:/var/www/html/index.php
    networks:
      - backend
      - frontend

  php:
    image: "php:7.4-fpm"
    volumes:
      - ./index.php:/var/www/html/index.php
    networks:
      - backend

  mysql:
    image: "mysql:8.0.33"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    networks:
      - backend

  phpmyadmin:
    image: "phpmyadmin:5.2.1"
    ports:
      - '6001:80'
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - backend

networks:
  backend:
  frontend:
